### ISSUE TITLE
How to set Fixed Framerate?

### ISSUE THREAD

**Issue by InactivatedPyschiopath** [apc-llc/moviemaker-cpp#3]
Hello and thanks for great library
It works on windows without any manipulation as well!

I have only one question how can I set the encoder to perform fixed framerate like 30.0 I played with c->framerate but it gives me float framerate like 38.52

**Comment by dmikushin** [comment]
Hello @InactivatedPyschiopath could you please check if #5 works for you? Please let us know, so that we can merge if it works well.
