### ISSUE TITLE
libx264 options has no effect on libvpx-vp

### ISSUE THREAD

**Issue by flm8620** [apc-llc/moviemaker-cpp#8]
In this two [lines](https://github.com/apc-llc/moviemaker-cpp/blob/9d771cda297bb68cd47c6050a313bd045cc7892f/src/writer.cpp#L48
),
```	
av_dict_set(&opt, "preset", "ultrafast", 0);
av_dict_set(&opt, "crf", "23", 0);
```
I found that these options has no effect on `libvpx-vp9` encoder you selected in previous line:
`AVCodec* codec = avcodec_find_encoder_by_name("libvpx-vp9");`

These options are from libx264 encoder.

**Comment by dmikushin** [comment]
Hi @flm8620 thank you for this report, would you like to go ahead and make a pull request? :pray:

**Comment by AndreiCherniaev** [comment]
@dmikushin I suggest close topic because of [commit](https://github.com/AndreiCherniaev/moviemaker-cpp_fix/commit/017f5f2b95ef7ceb6aa489d271ba76aae97c132e).

**Comment by dmikushin** [comment]
Yes, thank you!
